name: FactionShields
main: com.cloth.FactionShieldsPlugin
author: Cloth
version: 0.0.7
softdepend: [PlaceholderAPI]
commands:
  factionshield:
    description: Opens the faction shield GUI.
    aliases: [fs]